import type { Metadata } from "next";
import "./globals.css";
import { Link } from "@/components/Link";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { CourseSearch } from "@/components/CourseSearch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryClientProvider>
        <body className="overscroll-none scroll-smooth">
          <div className="flex flex-col gap-2 w-full">
            <div className="flex w-full border-b border-b-gray-200 py-2 px-4 justify-between sticky top-0 z-10 bg-white items-center">
              <Link href="/">Courses</Link>
              <CourseSearch />
            </div>
            <div className="p-4 pb-32">{children}</div>
          </div>
        </body>
      </ReactQueryClientProvider>
    </html>
  );
}
